server:
  port: 8003

spring:
  application:
    name: tminstructor-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    #      ddl-auto: create-drop

  datasource:
    url: jdbc:mysql://localhost/cs544?serverTimezone=GMT-6
    username: EA
    password: group2
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost