
server:

  port: 8002

spring:
  application:
    name: student-service

  datasource:
    url: jdbc:mysql://localhost/cs544?serverTimezone=GMT-6
    username: EA
    password: group2
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:

      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost



