
server:
  port: 8002

spring:
  application:
    name: student-service

  datasource:
    url: jdbc:mysql://localhost:3306/ea_project?serverTimezone=GMT-6
    username: root
    password: Bekalu12
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost



#server:
#  port: 8091
#
#spring:
#  application:
#    name: CoachService
#
#datasource:
#  url: jdbc:mysql://localhost/cs544?serverTimezone=GMT-6
#  username: EA
#  password: group2
#  driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#    preferIpAddress: true
