
#server:
# port: 8091
#spring:
# application:
#  name: smaple-spring-rest-service
# datasource:
#  url: jdbc:mysql://localhost/ea_project
#  username: ea
#  password: 201511
#  driver-class-name: com.mysql.cj.jdbc.Driver
# jpa:
#  show-sql: true
server.port=8097
spring.jpa.hibernate.ddl-auto= update
spring.datasource.url=jdbc:mysql://localhost:3306/ea_project?useSSL=false
spring.datasource.username=root
spring.datasource.password=Bekalu12
spring.jpa.show-sql=true
spring.jpa.database=mysql
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#sp






#server:
#  port: 8002
#
#spring:
#  application:
#    name: student-service
#
#  datasource:
#    url: jdbc:mysql://localhost/cs544?serverTimezone=GMT-6
#    username: EA
#    password: cs544
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8000/eureka
#    register-with-eureka: true
#    fetch-registry: true
#  instance:
#    hostname: localhost


