
server:
  port: 8085

spring:
  application:
    name: spring-boot-starter-parent

  datasource:
    url: jdbc:mysql://localhost/cs544?serverTimezone=GMT-6
    username: EA
    password: group2
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true


